# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180921_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_one_email',
            field=models.EmailField(default='No Email Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_two_email',
            field=models.EmailField(default='No Email Provided', max_length=255),
        ),
    ]
