# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180921_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_one_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_two_contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
