# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180923_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='unique_team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
