# Generated by Django 2.1.4 on 2018-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_unique_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_one_hall',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='player_two_hall',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
